[package]
name = "sandpack-cdn"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
actix-web = "4.0.0-beta.14"
semver = "1.0.4"
thiserror = "1.0.30"
env_logger = "0.9.0"
flate2 = "1.0.22"
tar = "0.4.37"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.72"
reqwest = { version = "0.11.7", features = ["json"] }
tokio = { version = "1.14.0", features = ["full"] }
redis = { version = "0.21.4", features = ["tokio-comp", "tokio-native-tls-comp"] }
url = "2.2.2"
glob = "0.3.0"
swc_ecmascript = { version = "0.88.3", features = ["parser", "transforms", "module", "optimization", "react", "typescript", "utils", "visit", "codegen", "utils"] }
swc_ecma_preset_env = "0.67.5"
swc_common = { version = "0.14.7", features = ["tty-emitter", "sourcemap"] }
swc_atoms = "0.2.9"
lazy_static = "1.4.0"
cached = "0.26.2"
