[package]
name = "sandpack-cdn"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
actix-web = "4.0.0-beta.12"
semver = "1"
thiserror = "1"
env_logger = "0.9"
flate2 = "1"
tar = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
redis = { version = "0.21.4", features = ["tokio-comp"] }
url = "2"
