[package]
name = "sandpack-cdn"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.0.0-beta.14"
actix-cors = "0.6.0-beta.6"
thiserror = "1.0.30"
env_logger = "0.9.0"
flate2 = "1.0.22"
tar = "0.4.37"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.72"
reqwest = { version = "0.11.7", features = ["json", "brotli", "gzip", "deflate"] }
tokio = { version = "1.14.0", features = ["full"] }
url = "2.2.2"
glob = "0.3.0"
swc_ecmascript = { version = "0.88.3", features = ["parser", "transforms", "module", "optimization", "react", "typescript", "utils", "visit", "codegen", "utils"] }
swc_ecma_preset_env = "0.67.5"
swc_common = { version = "0.14.7", features = ["tty-emitter", "sourcemap"] }
swc_atoms = "0.2.9"
lazy_static = "1.4.0"
lru = "0.7.0"
chrono = { version = "0.4.19", features = ["serde"] }
base64 = "0.13.0"
node-semver = "2.0.0"
futures = "0.3.17"
parking_lot = "0.11.2"
regex = "1.5.4"
