app = "sandpack-cdn-staging"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "8080"
NPM_SQLITE_DB = "/npm_db/registry.db3"
OTEL_SERVICE_NAME = "sandpack-cdn-staging"
OTEL_EXPORTER_OTLP_ENDPOINT = "https://api.honeycomb.io:443"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
type = "requests"
hard_limit = 200
soft_limit = 150

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = "5s"
grace_period = "2s"
method = "get"
path = "/health"
protocol = "http"
restart_limit = 6
timeout = "2s"
tls_skip_verify = true

[mounts]
source="npm_db"
destination="/npm_db"

# [deploy]
# strategy = "bluegreen"
