name: ci

on:
  push:
    branches:
      - 'ci'

env:
  workload_identity_provider: projects/140364730894/locations/global/workloadIdentityPools/codesandbox-microservices-pool/providers/github-actions-provider
  service_account: github-image-pusher-sa@codesandbox-microservices.iam.gserviceaccount.com

jobs:

  docker:
    runs-on: [self-hosted, default-runner]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: europe-docker.pkg.dev/codesandbox-microservices/codesandbox/sandpack-cdn
          tags: |
            type=sha

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ env.workload_identity_provider }}
          service_account: ${{ env.service_account }}
            
      - uses: docker/login-action@v2
        with:
          registry: europe-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
